###############################################################################
# Created by write_sdc
# Mon Jun  1 13:59:54 2026
###############################################################################
current_design Top
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 150.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rst}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[0]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[10]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[11]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[12]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[13]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[14]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[15]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[16]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[17]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[18]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[19]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[1]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[20]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[21]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[22]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[23]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[24]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[25]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[26]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[27]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[28]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[29]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[2]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[30]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[31]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[3]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[4]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[5]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[6]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[7]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[8]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out1[9]}]
set_output_delay 15.0000 -clock [get_clocks {clk}] -add_delay [get_ports {processor_out2}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {processor_out2}]
set_load -pin_load 0.0334 [get_ports {processor_out1[31]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[30]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[29]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[28]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[27]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[26]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[25]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[24]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[23]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[22]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[21]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[20]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[19]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[18]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[17]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[16]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[15]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[14]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[13]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[12]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[11]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[10]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[9]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[8]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[7]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[6]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[5]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[4]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[3]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[2]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[1]}]
set_load -pin_load 0.0334 [get_ports {processor_out1[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_1 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_1 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rst}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_fanout 6.0000 [current_design]
